---

- name: Create Ghost service

- name: fetch service ip/ load service ip/ set ghost ip/ set ghost ip in the inventory file

- name: create the ghost pod

- name: create tables

- name: create admin