---

- name: Create Ghost service
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ghost-service 
        labels:
          app: ghost
      spec:
        type: LoadBalancer
        selector:
          app: ghost
        ports:
          - protocol: TCP
            port: "{{ ghost-p}}"
            targetPort: "{{ ghost-tp}}"

- name: fetch service ip
  shell: "kubectl get -n default service ghost-service -o wide | awk '{ print $4}' |  grep -v EXT"
  register: k_ext_ip
  until: k_ext_ip.stdout[0] != "<"
  retries: 2
  delay: 15

- name: load service ip
  kubernetes.core.k8s_info:
    kind: Service
    label_selectors:
      - app=ghost
  register: ghost_service

  - name: set ghost ip
  set_fact:
    ghost_service_ip: "{{ ghost_service.resources[0].status.loadBalancer.ingress[0].ip }}"

- name: Set ghost ip in the inventory file
  template:
    src: gcp
    dest: inventory/gcp.yml

- name: create the ghost pod

- name: create tables

- name: create admin