- name: get db deployment
  kubernetes.core.k8s_info:
    kind: Deployment
    label_selectors:
      - app=mysql
      - tier=database
  register: mysql_deployment

- name: remove db deployment
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ mysql_deployment.resources[0] }}"

- name: get db service
  kubernetes.core.k8s_info:
    kind: Service
    label_selectors:
      - app=mysql
      - tier=database
  register: mysql_service

- name: remove db service
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ mysql_service.resources[0] }}"

- name: get db pvc
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
    label_selectors:
      - app=mysql
      - tier=database
  register: mysql_pvc

- name: remove db pvc
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ mysql_pvc.resources[0] }}"

- name: Replace ghost_ip in gcp.yml back to placeholder
  replace:
    path: inventory/gcp.yml
    regexp: 'ghost_ip: \s\S*'
    replace: 'ghost_ip: <GHOST_IP>'

- name: Replace ghost_ip in test file back to placeholder
  replace:
    path: inventory/gcp.yml
    regexp: '<stringProp name="HTTPSampler.domain">\S*</stringProp>'
    replace: '<stringProp name="HTTPSampler.domain">{{ ghost_ip }}</stringProp>'

