---
# Playbook to deploy Ghost and its components
- name: Deploy the ghost app and generate the database
  hosts: localhost
  gather_facts: false
  roles:
      - deploy-db
      - deploy-ghost
      - deploy-monitoring
