---

# - name: Create MySQL secret
#   k8s:
#     api_version: v1
#     kind: Secret
#     name: mysql-pass
#     namespace:  "{{ namespace }}"
#     definition:
#       spec:
#         data:
#           password: mypassword
#     state: present

- name: Create MySQL deployment
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: mysql
    namespace: "{{ namespace }}"
    src: "files/mysql-deployment.yml"

- name: Claim persistent volume for MySQL
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: PersistentVolumeClaim
    name: mysql
    namespace: "{{ namespace }}"
    src: "mysql-pvc.yml"

- name: Create MySQL service
  kubernetes.core.k8s:
    api_version: v1
    kind: Service
    name: mysql
    namespace: "{{ namespace }}"
    src: "mysql-service.yml"
